sudo: false
language: python
python: 
  - "3.5"
install: 
  - "pip install -r requirements.txt"
  - "pip install -r requirements_test.txt"
  - "pip install lxml html5lib gevent cchardet"
  - "pip install pylinkvalidator"
script:
  - "py.test"
  - "flake8 tests"
  - "sphinx-build docs output"
  - "cd output; python -m http.server 8000 &  ; sleep 5 ; pylinkvalidate.py --console http://localhost:8080/"
